services:
  web:
    build: .
    ports:
      - "8080:80"      
    volumes:
      - ./first_website:/var/www/html          
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge
